name: Delete Repo
description: Creates a repository within an organization using the gh CLI.

inputs:
  USER_PAT:
    description: 'Enter the Personal Access Token'
    required: true
  ORG_NAME:
    description: 'Enter organization name'
    required: true
  REPO_NAME:
    description: 'Enter name of repository'
    required: true    

runs:
  using: composite
  steps:

      - name: Delete Repo
        id: Repo_ID
        env:
         GITHUB_TOKEN: ${{ inputs.USER_PAT }}
        run: |
          gh api \
          --method DELETE \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/${{ inputs.ORG_NAME }}/${{ inputs.REPO_NAME }}        
        
        shell: bash  
