name: test-delete-repo

on:
  workflow_dispatch:
    inputs:
      ORG_NAME:
        description: 'Enter organization name'
        required: true
      REPO_NAME:
        description: 'Enter name of repository'
        required: true
jobs:
  delete-repo:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install gh CLI
      run: |
        sudo apt-get update
        sudo apt-get install gh

    - name: Login to GitHub
      run: |
        gh auth login --with-token <<< "${{ secrets.ISSUE_OPS_TOKEN }}"

    - name: Delete repository
      uses: ./provisioner/actions/delete-repo
      with:
        USER_PAT: ${{ secrets.ISSUE_OPS_TOKEN }}
        ORG_NAME: ${{ github.event.inputs.ORG_NAME }}
        REPO_NAME: ${{ github.event.inputs.REPO_NAME }}